/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module mux2(a, b, sel, y);
  input a;
  wire a;
  input b;
  wire b;
  input sel;
  wire sel;
  output y;
  wire y;
  assign y = sel ? b : a;
endmodule

module mux_4to1(d0, d1, d2, d3, s, y);
  input [3:0] d0;
  wire [3:0] d0;
  input [3:0] d1;
  wire [3:0] d1;
  input [3:0] d2;
  wire [3:0] d2;
  input [3:0] d3;
  wire [3:0] d3;
  wire high;
  wire low;
  input [1:0] s;
  wire [1:0] s;
  output [3:0] y;
  wire [3:0] y;
  mux2 finalmux (
    .a(low),
    .b(high),
    .sel(s[1]),
    .y(y[0])
  );
  mux2 highmux (
    .a(d2[0]),
    .b(d3[0]),
    .sel(s[0]),
    .y(high)
  );
  mux2 lowmux (
    .a(d0[0]),
    .b(d1[0]),
    .sel(s[0]),
    .y(low)
  );
  assign y[3:1] = 3'h0;
endmodule
